name: LootsToolsSpigot
main: com.darye.lootstoolsmc.LootsToolsSpigotPlugin
version: 1.0
api-version: 1.17
commands:
  caneat:
    description: Your description
    usage: /caneat <item> <time> <feedValue>
    permission: lootstools.op
  kit:
    description: Your description
    usage: /<command>
    permission: lootstools.op
permissions:
  lootstools.*:
    description: a
    children:
      lootstools.op: true
  lootstools.op:
    description: Permisos de OP
    default: op
